// Code generated by MockGen. DO NOT EDIT.
// Source: /home/wil/dev/sro/go-common-service/pkg/bus/gameserver/dimensionbus/service.go
//
// Generated by this command:
//
//	mockgen -source=/home/wil/dev/sro/go-common-service/pkg/bus/gameserver/dimensionbus/service.go -destination=/home/wil/dev/sro/go-common-service/pkg/bus/gameserver/dimensionbus/mocks/service.go
//

// Package mock_dimensionbus is a generated GoMock package.
package mock_dimensionbus

import (
	context "context"
	reflect "reflect"

	bus "github.com/ShatteredRealms/go-common-service/pkg/bus"
	dimensionbus "github.com/ShatteredRealms/go-common-service/pkg/bus/gameserver/dimensionbus"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetDimensionById mocks base method.
func (m *MockService) GetDimensionById(ctx context.Context, dimensionId string) (*dimensionbus.Dimension, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDimensionById", ctx, dimensionId)
	ret0, _ := ret[0].(*dimensionbus.Dimension)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDimensionById indicates an expected call of GetDimensionById.
func (mr *MockServiceMockRecorder) GetDimensionById(ctx, dimensionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDimensionById", reflect.TypeOf((*MockService)(nil).GetDimensionById), ctx, dimensionId)
}

// GetDimensions mocks base method.
func (m *MockService) GetDimensions(ctx context.Context) (*dimensionbus.Dimensions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDimensions", ctx)
	ret0, _ := ret[0].(*dimensionbus.Dimensions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDimensions indicates an expected call of GetDimensions.
func (mr *MockServiceMockRecorder) GetDimensions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDimensions", reflect.TypeOf((*MockService)(nil).GetDimensions), ctx)
}

// GetResetter mocks base method.
func (m *MockService) GetResetter() bus.Resettable {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResetter")
	ret0, _ := ret[0].(bus.Resettable)
	return ret0
}

// GetResetter indicates an expected call of GetResetter.
func (mr *MockServiceMockRecorder) GetResetter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResetter", reflect.TypeOf((*MockService)(nil).GetResetter))
}

// IsProcessing mocks base method.
func (m *MockService) IsProcessing() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProcessing")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProcessing indicates an expected call of IsProcessing.
func (mr *MockServiceMockRecorder) IsProcessing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProcessing", reflect.TypeOf((*MockService)(nil).IsProcessing))
}

// RegisterListener mocks base method.
func (m *MockService) RegisterListener(listener bus.BusListener[dimensionbus.Message]) bus.BusListenerHandler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterListener", listener)
	ret0, _ := ret[0].(bus.BusListenerHandler)
	return ret0
}

// RegisterListener indicates an expected call of RegisterListener.
func (mr *MockServiceMockRecorder) RegisterListener(listener any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterListener", reflect.TypeOf((*MockService)(nil).RegisterListener), listener)
}

// RemoveListener mocks base method.
func (m *MockService) RemoveListener(listenerHandle bus.BusListenerHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveListener", listenerHandle)
}

// RemoveListener indicates an expected call of RemoveListener.
func (mr *MockServiceMockRecorder) RemoveListener(listenerHandle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveListener", reflect.TypeOf((*MockService)(nil).RemoveListener), listenerHandle)
}

// StartProcessing mocks base method.
func (m *MockService) StartProcessing(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartProcessing", ctx)
}

// StartProcessing indicates an expected call of StartProcessing.
func (mr *MockServiceMockRecorder) StartProcessing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartProcessing", reflect.TypeOf((*MockService)(nil).StartProcessing), ctx)
}

// StopProcessing mocks base method.
func (m *MockService) StopProcessing() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopProcessing")
}

// StopProcessing indicates an expected call of StopProcessing.
func (mr *MockServiceMockRecorder) StopProcessing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopProcessing", reflect.TypeOf((*MockService)(nil).StopProcessing))
}
