// Code generated by MockGen. DO NOT EDIT.
// Source: /home/wil/sro/go-common-service/pkg/bus/character/characterbus/repository.go
//
// Generated by this command:
//
//	mockgen -source=/home/wil/sro/go-common-service/pkg/bus/character/characterbus/repository.go -destination=/home/wil/sro/go-common-service/pkg/bus/character/characterbus/mocks/repository.go
//

// Package mock_characterbus is a generated GoMock package.
package mock_characterbus

import (
	context "context"
	reflect "reflect"

	characterbus "github.com/ShatteredRealms/go-common-service/pkg/bus/character/characterbus"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id *uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockRepository) GetAll(ctx context.Context) (*characterbus.Characters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].(*characterbus.Characters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRepository)(nil).GetAll), ctx)
}

// GetById mocks base method.
func (m *MockRepository) GetById(ctx context.Context, characterId *uuid.UUID) (*characterbus.Character, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, characterId)
	ret0, _ := ret[0].(*characterbus.Character)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockRepositoryMockRecorder) GetById(ctx, characterId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockRepository)(nil).GetById), ctx, characterId)
}

// GetByOwnerId mocks base method.
func (m *MockRepository) GetByOwnerId(ctx context.Context, ownerId *uuid.UUID) (*characterbus.Characters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOwnerId", ctx, ownerId)
	ret0, _ := ret[0].(*characterbus.Characters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOwnerId indicates an expected call of GetByOwnerId.
func (mr *MockRepositoryMockRecorder) GetByOwnerId(ctx, ownerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOwnerId", reflect.TypeOf((*MockRepository)(nil).GetByOwnerId), ctx, ownerId)
}

// IsOwner mocks base method.
func (m *MockRepository) IsOwner(ctx context.Context, characterId, ownerId *uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOwner", ctx, characterId, ownerId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsOwner indicates an expected call of IsOwner.
func (mr *MockRepositoryMockRecorder) IsOwner(ctx, characterId, ownerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOwner", reflect.TypeOf((*MockRepository)(nil).IsOwner), ctx, characterId, ownerId)
}

// Save mocks base method.
func (m *MockRepository) Save(ctx context.Context, data characterbus.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), ctx, data)
}
